# Generated by Django 4.1.6 on 2023-02-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First Name', models.CharField(max_length=200)),
                ('Last Name', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('age', models.IntegerField()),
                ('Password', models.CharField(max_length=50)),
                ('Confirm Password', models.CharField(max_length=50)),
                ('registration_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='servicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicePlanName', models.CharField(max_length=30)),
                ('servicePlanDuration', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('userFirstName', models.CharField(max_length=200)),
                ('userLastName', models.CharField(max_length=200)),
                ('userEmail', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicePlanStartDate', models.DateTimeField(max_length=30)),
                ('servicePlanEndDate', models.DateTimeField(max_length=30)),
                ('servicePlanDateLeft', models.DateTimeField(max_length=30)),
            ],
        ),
    ]
