# Generated by Django 4.1.6 on 2023-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwd5App', '0003_usermodel_delete_register_delete_serviceplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
