# Generated by Django 4.1.6 on 2023-02-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwd5App', '0004_usermodel_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='serviceRemainDay',
            new_name='serviceExpireDate',
        ),
    ]
